version: '3.9'

services:
  app:
    build: .
    container_name: "newsPortalService"
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/news_portal
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - REDIS_HOST=redis_cache
      - REDIS_PORT=6379
    depends_on:
      - postgres

  postgres:
    image: 'postgres:14'
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: news_portal
    ports:
      - "5432:5432"
    volumes:
      - ./src/main/resources/db/migration:/docker-entrypoint-initdb.d

  redis_cache:
    image: redis
    container_name: redis_cache
    ports:
      - "6379:6379"
