CREATE TABLE role (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                   role_name varchar NOT NULL UNIQUE);

CREATE TABLE app_user (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       email varchar NOT NULL UNIQUE,
                       password varchar NOT NULL);

CREATE TABLE user_role (user_id bigint not null references app_user (id),
                        role_id bigint not null references role (id),
                        primary key (user_id, role_id));

CREATE TABLE category (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       category_name varchar NOT NULL,
                       parent_id bigint DEFAULT NULL REFERENCES category (id));

CREATE TABLE article (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      headline varchar NOT NULL,
                      content varchar NOT NULL,
                      created_date timestamp NOT NULL,
                      updated_date timestamp DEFAULT NULL,
                      user_id bigint NOT NULL REFERENCES app_user (id),
                      category_id bigint NOT NULL REFERENCES category (id));


insert into role (role_name) values ('ROLE_USER'), ('ROLE_AUTHOR'), ('ROLE_ADMIN');
insert into app_user (email, password) values ('user1@mail.com', '$2a$10$TFbAZUdnG1943FLvFw.34efzhDH3OYv55BJPs179jNMPdoWHSKxRi');
insert into app_user (email, password) values ('admin1@mail.com', '$2a$10$LiAc5MifM4g.qqHTKVm.z.vuNH5HrZLwliqHTNaFJwjsi6he.i/W6');
insert into user_role (user_id, role_id) values (1, 1), (1, 2), (2, 3);