CREATE TABLE role (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                   role_name varchar NOT NULL UNIQUE);

CREATE TABLE app_user (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       email varchar NOT NULL UNIQUE,
                       password varchar NOT NULL);

CREATE TABLE user_role (user_id bigint not null references app_user (id),
                        role_id bigint not null references role (id),
                        primary key (user_id, role_id));

CREATE TABLE category (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       category_name varchar NOT NULL,
                       parent_id bigint DEFAULT NULL REFERENCES category (id));

CREATE TABLE article (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      headline varchar NOT NULL,
                      content varchar NOT NULL,
                      created_date timestamp NOT NULL,
                      updated_date timestamp DEFAULT NULL,
                      user_id bigint NOT NULL REFERENCES app_user (id),
                      category_id bigint NOT NULL REFERENCES category (id));


insert into role (role_name) values ('ROLE_USER'), ('ROLE_AUTHOR'), ('ROLE_ADMIN');
insert into app_user (email, password) values ('author@mail.com', '$2a$10$TFbAZUdnG1943FLvFw.34efzhDH3OYv55BJPs179jNMPdoWHSKxRi');
insert into app_user (email, password) values ('admin@mail.com', '$2a$10$LiAc5MifM4g.qqHTKVm.z.vuNH5HrZLwliqHTNaFJwjsi6he.i/W6');
insert into app_user (email, password) values ('user@mail.com', '$2a$10$LiAc5MifM4g.qqHTKVm.z.vuNH5HrZLwliqHTNaFJwjsi6he.i/W6');
insert into user_role (user_id, role_id) values (1, 1), (1, 2), (2, 3), (3, 1);
insert into category (category_name, parent_id) values ('News', null), ('Sport', null);
insert into category (category_name, parent_id) values ('Europe', 1), ('Australia', 1), ('Formula 1', 2), ('Football', 2);
insert into article (headline, content, category_id, user_id, created_date) values ('Banned something', 'Experts have raised concerns, leading to the initiation of a significant crackdown', 4, 1, now());
insert into article (headline, content, category_id, user_id, created_date) values ('The Australian campus', 'Although the majority of his education was acquired through boarding schools, he was enrolled in a campus...', 4, 1, now());
insert into article (headline, content, category_id, user_id, created_date) values ('Eurovision', 'Only a few days remain until the competition, and its presenter reminisces about the excitement of hosting the show.', 3, 1, now());
insert into article (headline, content, category_id, user_id, created_date) values ('Miami Grand Prix practice', 'Someone demonstrated his racing prowess, aided by the safety car, to outpace his teammate and claim victory at the Grand Prix.', 5, 1, now());
insert into article (headline, content, category_id, user_id, created_date) values ('Grand Prix', 'Someone emerged as the victor in his RedBull after one of the most dramatic races in recent memory, which was anything but predictable.', 5, 1, now());
insert into article (headline, content, category_id, user_id, created_date) values ('Football', 'He is optimistic that they will achieve a top-four finish in the Premier League, and he believes they have what it takes to make it happen and cross the finish line.', 6, 1, now());
